#ifndef _CONFIG_H
#define _CONFIG_H

#define RAOS_TOTAL_INTERRUPTS 512

// define in kernel.asm CODE_SEG, DATA_SEG
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b


// Naive implementation. 100M size of kernel heap.
#define RAOS_HEAP_SIZE_BYTES 104857600
#define RAOS_HEAP_BLOCK_SIZE 4096

#define RAOS_HEAP_ADDRESS 0x01000000
#define RAOS_HEAP_TABLE_ADDRESS 0x00007E00

#define RAOS_SECTOR_SIZE 512

#define RAOS_MAX_FILESYSTEMS 16
#define RAOS_MAX_FILE_DESCRIPTORS 512

#define RAOS_MAX_PATH 128

#define RAOS_TOTAL_GDT_SEGMENTS 6


#define RAOS_MAX_PROCESSES 12

#define RAOS_MAX_PROGRAM_ALLOCATIONS 1024

#define RAOS_USER_PROGRAM_STACK_SIZE 1024 * 16


#define RAOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define RAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define RAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END RAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - RAOS_USER_PROGRAM_STACK_SIZE


#define RAOS_MAX_ISR80H_COMMANDS 1024


#define RAOS_KEYBOARD_BUFFER_SIZE 1024

#endif